
. "$PSScriptRoot\functions\RunChunkedSql.ps1" # include Invoke-ChunkedSql
. "$PSScriptRoot\functions\GetDbConnectionString.ps1" # include Get-ConnectionString

$file = "$PSScriptRoot\..\sql\datapump\ChunkedAlterFilterViews.sql"
$logfile = "$PSScriptRoot\..\log\AlterFilterViews.log"

$connectionString = Get-ConnectionString


Invoke-ChunkedSql -SqlFile $file -LogFile $logfile -ConnectionString $connectionString

# SIG # Begin signature block
# MIIFhQYJKoZIhvcNAQcCoIIFdjCCBXICAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUDy7HsijCBP2065A86XKfzyZA
# mJegggMYMIIDFDCCAfygAwIBAgIQegXJmptVUKlJaZjT11rO5zANBgkqhkiG9w0B
# AQsFADAiMSAwHgYDVQQDDBdQb3dlclNoZWxsIENvZGUgU2lnbmluZzAeFw0yMDEx
# MjMxMzI3MTdaFw0yMTExMjMxMzQ3MTdaMCIxIDAeBgNVBAMMF1Bvd2VyU2hlbGwg
# Q29kZSBTaWduaW5nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwqYE
# crJmGUyG4WAqNXC0A5vLvEMJQiIOouBBdbvDDnkcm/Uub4H4/PktWLi+13NH6CXY
# 6zuLoJOxcXAlqsQiRQUJwHxzoOOa5sjBd8cQexWq2FPm67oPcJJPP2m7iVqChNJF
# 8VS8z/9T+CYMSZL5M1WVMBckt8q3lqSIOH1a0ExoTnXwDKCoPDW+qVep0iAk2pm6
# jPotT0yW3Yzl69Rm3JXHW6altEtXIArV0/wqFLdrp9BaAPTdXaMJNcK3KRW6Brrj
# kD4T7kXooAWeQ4Sgi98zWNRe1+KJEjpt3lae7jHd+ispTrJG2NLh3Mx1OYT4qSQ/
# E38iLUAE/N65Fs5ZJQIDAQABo0YwRDAOBgNVHQ8BAf8EBAMCB4AwEwYDVR0lBAww
# CgYIKwYBBQUHAwMwHQYDVR0OBBYEFK488ebRUMrXQTkLqDfrB1rOpvPZMA0GCSqG
# SIb3DQEBCwUAA4IBAQC3eCvjxsTLVpEB4bh7/5LXk2wm2uLpMxt/+BJnOXQc8neA
# mzB6CvlG8HR04n/iZC6iYQIHjIqBGdBtAYvBTFpukqb1x2J443wXR4Ba9hpFvLIf
# +yb45TuhoR8qqX6xC87HGVJ5lXSOVwG/PFtgNj5dZIqd7p8VbK7ATzYU4GDqaPYr
# UHsTcYvaOXlHA5J+Wuf7wti8jH5u6fLuQc2JCB0RdIjSeOiIbtxyoZBaZGlC8Hpy
# 9yeMqghA8+JRiq4L9a58nEsO8/m4cSk3NvF7OIll7e80TixoKGKe1LscvPBFoot/
# ulqsP7ks4Wf+zGnmurrsz/yqwJcBGu3Ltb3pR6vHMYIB1zCCAdMCAQEwNjAiMSAw
# HgYDVQQDDBdQb3dlclNoZWxsIENvZGUgU2lnbmluZwIQegXJmptVUKlJaZjT11rO
# 5zAJBgUrDgMCGgUAoHgwGAYKKwYBBAGCNwIBDDEKMAigAoAAoQKAADAZBgkqhkiG
# 9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgorBgEEAYI3AgELMQ4wDAYKKwYBBAGCNwIB
# FTAjBgkqhkiG9w0BCQQxFgQU7PLhsBzYGMRZbs8cIs+/bqwa/MEwDQYJKoZIhvcN
# AQEBBQAEggEAWB4qThxRtDHsLLI91D+9aSbavYrGDov6EngvrbEy0zk9HQhhHCN1
# pbcrZDHI+LayQzPMjbnUTG19chBs33L0wlh9Hiu9LR3dJyvOyqgvnXUlX+zcOAwB
# 8IGcgVZuQzxV14QUNvmaNBx4dToSiEwDCmKARb+vUd7FVtFuSmbHM8Kzug5uw8pq
# lJpkG0gwh3DCb9U02qLYANG6pNkxmh38j+7qLv/+790M1KmOddBWlOiBuZdqiRTt
# BymXzTh6Le0dR1zZabOGEpoep1q8l5wFIpzqYK+U+lb4egFlDjNjxmOudE2CDKTB
# /D6Dnuph3TS/gAhKzMgOUVJCbYz5oYzpTg==
# SIG # End signature block
