for($i = 1; $i -lt 11; $i++ ) {
  Write-Progress -Id 0 "Step $i" -PercentComplete ($i*10)
  for($j = 1; $j -lt 11; $j++ ) {
    Write-Progress -Id 1 -ParentId 0 "Step $i - Substep $j"  -PercentComplete ($j * 10)
    for($k = 1; $k -lt 11; $k++ ) {
      Write-Progress -Id 2  -ParentId 1 "Step $i - Substep $j - iteration $k"  -PercentComplete ($k * 10); start-sleep -m 50
    }
  }
}
# SIG # Begin signature block
# MIIFhQYJKoZIhvcNAQcCoIIFdjCCBXICAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQUUV6iVVmJY/kG/Y8wfDUhMM+j
# NCegggMYMIIDFDCCAfygAwIBAgIQegXJmptVUKlJaZjT11rO5zANBgkqhkiG9w0B
# AQsFADAiMSAwHgYDVQQDDBdQb3dlclNoZWxsIENvZGUgU2lnbmluZzAeFw0yMDEx
# MjMxMzI3MTdaFw0yMTExMjMxMzQ3MTdaMCIxIDAeBgNVBAMMF1Bvd2VyU2hlbGwg
# Q29kZSBTaWduaW5nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwqYE
# crJmGUyG4WAqNXC0A5vLvEMJQiIOouBBdbvDDnkcm/Uub4H4/PktWLi+13NH6CXY
# 6zuLoJOxcXAlqsQiRQUJwHxzoOOa5sjBd8cQexWq2FPm67oPcJJPP2m7iVqChNJF
# 8VS8z/9T+CYMSZL5M1WVMBckt8q3lqSIOH1a0ExoTnXwDKCoPDW+qVep0iAk2pm6
# jPotT0yW3Yzl69Rm3JXHW6altEtXIArV0/wqFLdrp9BaAPTdXaMJNcK3KRW6Brrj
# kD4T7kXooAWeQ4Sgi98zWNRe1+KJEjpt3lae7jHd+ispTrJG2NLh3Mx1OYT4qSQ/
# E38iLUAE/N65Fs5ZJQIDAQABo0YwRDAOBgNVHQ8BAf8EBAMCB4AwEwYDVR0lBAww
# CgYIKwYBBQUHAwMwHQYDVR0OBBYEFK488ebRUMrXQTkLqDfrB1rOpvPZMA0GCSqG
# SIb3DQEBCwUAA4IBAQC3eCvjxsTLVpEB4bh7/5LXk2wm2uLpMxt/+BJnOXQc8neA
# mzB6CvlG8HR04n/iZC6iYQIHjIqBGdBtAYvBTFpukqb1x2J443wXR4Ba9hpFvLIf
# +yb45TuhoR8qqX6xC87HGVJ5lXSOVwG/PFtgNj5dZIqd7p8VbK7ATzYU4GDqaPYr
# UHsTcYvaOXlHA5J+Wuf7wti8jH5u6fLuQc2JCB0RdIjSeOiIbtxyoZBaZGlC8Hpy
# 9yeMqghA8+JRiq4L9a58nEsO8/m4cSk3NvF7OIll7e80TixoKGKe1LscvPBFoot/
# ulqsP7ks4Wf+zGnmurrsz/yqwJcBGu3Ltb3pR6vHMYIB1zCCAdMCAQEwNjAiMSAw
# HgYDVQQDDBdQb3dlclNoZWxsIENvZGUgU2lnbmluZwIQegXJmptVUKlJaZjT11rO
# 5zAJBgUrDgMCGgUAoHgwGAYKKwYBBAGCNwIBDDEKMAigAoAAoQKAADAZBgkqhkiG
# 9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgorBgEEAYI3AgELMQ4wDAYKKwYBBAGCNwIB
# FTAjBgkqhkiG9w0BCQQxFgQUNMy+diDw9UgK5YDFDUdudGd/ycYwDQYJKoZIhvcN
# AQEBBQAEggEAheC0LUxNnPqX9fX3j206NZmbzNrSmqT4MCmafRxmyg6EGpxs2LXz
# TdtEPR6glOSyJzYKWU5A68MEp90NKnxuvLqLnxQGtGuG3ny5eaD0BHENvUVIZmPj
# KyiqvMOb5qnnnsXswx5uKkVm2+snojA/qEe4Ljj97PIhdjZtYLF7kRX/WqFqU8uR
# m7UivTxtwbGHkvJLucpA6W8IFv+UjCH9vuhGC+6vLDMjGFSTHo0XLYCAzdgwzw0w
# nLzurWncU1MKGDyyKH8i8P9gLTk0HJ8Ax8pyukOv/x7Y1NHL8ConHfyhqDZOF+Rc
# 2HBCKMU/lGHOcdawPlq6XDAReN2TMKUGUg==
# SIG # End signature block
